"""add name column to user

Revision ID: 9c8cda513769
Revises: new_revision_id_here
Create Date: 2025-09-26 16:53:46.158025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c8cda513769'
down_revision: Union[str, Sequence[str], None] = 'new_revision_id_here'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=True))
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'student'"))
    op.drop_index(op.f('ix_User_id'), table_name='user')
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.create_index(op.f('ix_User_id'), 'user', ['id'], unique=False)
    op.alter_column('user', 'role',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'student'"))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
