"""add published_year column to books

Revision ID: 9f606014788e
Revises: b8d76a0bc905
Create Date: 2025-09-19 18:16:52.338103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f606014788e'
down_revision: Union[str, Sequence[str], None] = 'b8d76a0bc905'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'published_year')
    # ### end Alembic commands ###
